pumps {
  name: "bottom_left"
  i2c_pin_number: 0
}
pumps {
  name: "bottom_right"
  i2c_pin_number: 1
}
pumps {
  name: "middle_left"
  i2c_pin_number: 2
}
pumps {
  name: "middle_right"
  i2c_pin_number: 3
}
pumps {
  name: "unused_1"
  i2c_pin_number: 4
}
pumps {
  name: "unused_2"
  i2c_pin_number: 5
}
plants {
  name: "Bottom Left"
  pump_name: "bottom_left"
}
plants {
  name: "Bottom Right"
  pump_name: "bottom_right"
}
plants {
  name: "Middle Left"
  pump_name: "middle_left"
}
plants {
  name: "Middle Right"
  pump_name: "middle_right"
}
plants {
  name: "Unused 1"
  pump_name: "unused_1"
}
plants {
  name: "Unused 2"
  pump_name: "unused_2"
}
