pumps {
  name: "one"
  i2c_pin_number: 0
}
pumps {
  name: "two"
  i2c_pin_number: 1
}
pumps {
  name: "three"
  i2c_pin_number: 2
}
pumps {
  name: "four"
  i2c_pin_number: 3
}
pumps {
  name: "five"
  i2c_pin_number: 4
}
pumps {
  name: "six"
  i2c_pin_number: 5
}
plants {
  name: "36 Cell Planter"
  pump_name: "one"
}
plants {
  name: "6 Net Cup Planter"
  pump_name: "two"
}
plants {
  name: "12 Net Cup Planter"
  pump_name: "three"
}
actions {
  plant_name: "36 Cell Planter"
  action: WATER
  tick {
    weekly {
      day_of_week: TUESDAY
      day_of_week: THURSDAY
      day_of_week: SATURDAY
      hour: 8
      min: 30
    }
  }
  duration_secs: 600
}
actions {
  plant_name: "6 Net Cup Planter"
  action: WATER
  tick {
    weekly {
      day_of_week: TUESDAY
      day_of_week: THURSDAY
      day_of_week: SATURDAY
      hour: 8
      min: 30
    }
  }
  duration_secs: 540
}
actions {
  plant_name: "12 Net Cup Planter"
  action: WATER
  tick {
    weekly {
      day_of_week: TUESDAY
      day_of_week: THURSDAY
      day_of_week: SATURDAY
      hour: 8
      min: 30
    }
  }
  duration_secs: 900
}
actions {
  plant_name: "36 Cell Planter"
  action: PICTURE
  tick {
    weekly {
      day_of_week: MONDAY
      day_of_week: TUESDAY
      day_of_week: WEDNESDAY
      day_of_week: THURSDAY
      day_of_week: FRIDAY
      day_of_week: SATURDAY
      day_of_week: SUNDAY
      hour: 9
      min: 30
    }
  }
}
