pumps {
  name: "bottom_right"
  gpio_pin_number: 14
}
pumps {
  name: "bottom_left"
  gpio_pin_number: 15
}
pumps {
  name: "top_right"
  gpio_pin_number: 18
}
pumps {
  name: "top_left"
  gpio_pin_number: 23
}
